{% set name = "conway-polynomials" %}
{% set version = "0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4f619f64f81a3eb16c4e26c5a284feeec27a6f4aad647643e79af289801ae0f3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - pip
  run:
    - python >=3.9

test:
  imports:
    - conway_polynomials
  commands:
    - pip check
    - "pytest --doctest-modules --doctest-glob='*.py'"
  requires:
    - pip
    - pytest

about:
  home: https://github.com/sagemath/conway-polynomials
  summary: Python interface to Frank Lübeck's Conway polynomial database
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tobiasdiez
    - saraedum
